services:
  sprawdziany:
    build:
      context: ./next
      dockerfile: Dockerfile
    image: sprawdziany:latest
    container_name: sprawdziany
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - NEXT_PUBLIC_WS_URL=/api/ws
      - PORT=3000
      - SMTP_HOST=${SMTP_HOST:-localhost}
      - SMTP_PORT=${SMTP_PORT:-25}
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - SMTP_FROM=${SMTP_FROM:-sprawdziany@example.com}
    volumes:
      - ./next/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sprawdziany.rule=Host(`sprawdziany.vps.malejka.lowicz.pl`)"
      - "traefik.http.routers.sprawdziany.entrypoints=websecure"
      - "traefik.http.routers.sprawdziany.tls.certresolver=myresolver"
      - "traefik.http.services.sprawdziany-service.loadbalancer.server.port=3000"
    networks:
      - proxy

networks:
  proxy:
    external: true